### ISSUE TITLE
Convite para o Discord Inválido

### ISSUE THREAD

**Issue by MoisesTedeschi** [Garden-Projects/30-Dias-de-Flask#1]
Ao que parece, o convite para o grupo do [Discorde](https://discord.com/invite/UVbHSHV4) está inválido. Sendo assim, o projeto foi descontinuado ou ainda está valendo?
Gostaria de participar dos "30 dias de Flask".

Grato pela atenção!

**Comment by LuanComputacao** [comment]
Olá @MoisesTedeschi !
Acabei de modificar o link para o Discord, colocando um que não vai inspirar.
Thanks!
